### PR TITLE
fix: clamp and parse H4 titles in ToC

### LINKED ISSUE #172: docs: header links are broken for H4 elements in markdown
See the intro docs at https://docs.pmnd.rs/react-three-fiber. Headers beneath the "why" segment aren't accessible via the page links nor point to a valid URL.

image

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixes #172 by also parsing level 4 headers and clamping to avoid unexpected behavior with other levels. Headings of any kind are in the side table of contents, with subheadings (those above level 2, the minimum) indented to indicate hierarchy.

Styles were deduped in the process, contained in the `Heading` component.

### CODE REVIEW

File: components/mdx/index.tsx [hunk 1]
```diff
@@ -37,24 +37,17 @@ const components = {
...
   Heading: ({ children, id, level }) => {
-    const Comp = level === 2 ? 'h2' : 'h3'
+    const headingStyle = {
+      2: 'text-3xl mb-6 mt-8',
+      3: 'text-xl mb-4 mt-6',
+      4: 'text-base mb-4 mt-4',
+    }
+
+    const clampedLevel = Math.min(Math.max(level, 2), 4)
+    const Comp = `h${clampedLevel}`
```
Comment (CodyJasonBennett) [inline components/mdx/index.tsx:48]: TS is not recognizing this as a react element that accepts `children` and `id` props.

Comment (CodyJasonBennett) [inline components/mdx/index.tsx:48]: TS is not recognizing this as a react element that accepts `children` and `id` props.
